export const propic = require('./images/icons/profile pic.png');
export const image = require('./images/icons/Image.png');
export const gif = require('./images/icons/gif.png');
export const poll = require('./images/icons/poll.png');
export const emoji = require('./images/icons/emoji.png');
export const schedule = require('./images/icons/schedule.png');
export const eyeglass = require('./images/eyeglass.png');
export const ppl = require('./images/ppl.png');
export const bubble = require('./images/bubble.png');
export const birb = require('./images/birb.png');
export const whiteBirb = require('./images/white-birb.png');
export const house = require('./images/icons/lil house.png');
export const bluHouse = require('./images/icons/lil blu house.png');
export const hashtag = require('./images/icons/hashtag.png');
export const bluHashtag = require('./images/icons/blu hashtag.png');
export const bell = require('./images/icons/bell.png');
export const bluBell = require('./images/icons/blu bell.png');
export const envelope = require('./images/icons/envelope.png');
export const bluEnvelope = require('./images/icons/blu envelope.png');
export const bookmark = require('./images/icons/bookmark.png');
export const bluBookmark = require('./images/icons/blu bookmark.png')
export const list = require('./images/icons/list.png');
export const bluList = require('./images/icons/blu list.png')
export const more = require('./images/icons/more.png');
export const quill = require('./images/icons/quill.png');
export const addTweed = require('./images/icons/add tweed.png');